version: '3.8'

services:
  shidouh-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: shidouh-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production 